import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const repoRoot = fileURLToPath(new URL('../../..', import.meta.url));
const artifactPaths = [
	'DESIGN.md',
	'apps/gallery/src/app.css',
	'packages/motion/src/tokens.ts',
	'packages/tokens/tokens.css',
] as const;

function sourceFiles(directory: string): string[] {
	return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
		const path = join(directory, entry.name);
		return entry.isDirectory() ? sourceFiles(path) : path.endsWith('.ts') ? [path] : [];
	});
}

describe('token artifact ownership', () => {
	it('maps every logical output to its committed repository artifact', () => {
		const check = spawnSync('bun', ['tools/build-tokens.ts', '--check'], {
			cwd: repoRoot,
			encoding: 'utf8',
		});

		expect(check.status, check.stderr).toBe(0);
		expect(check.stdout).toContain('build idempotent (no changes)');
		for (const path of artifactPaths) {
			expect(existsSync(new URL(`../../../${path}`, import.meta.url)), path).toBe(true);
		}
	});

	it('makes the gallery consume the package artifact without a local mirror', () => {
		const appCss = readFileSync(new URL('../src/app.css', import.meta.url), 'utf8');

		expect(appCss).toContain("@import '@yesid/tokens/tokens.css';");
		expect(existsSync(new URL('../src/lib/styles/tokens.css', import.meta.url))).toBe(false);
	});

	it('keeps consumer paths out of the upstream token package', () => {
		const upstreamFiles = [
			join(repoRoot, 'packages/tokens/package.json'),
			...sourceFiles(join(repoRoot, 'packages/tokens/src')),
		];
		for (const path of upstreamFiles) {
			const source = readFileSync(path, 'utf8');
			expect(source, path).not.toMatch(/apps\/gallery|packages\/motion|\.\.\/\.\.\/DESIGN\.md/);
		}
	});

	it('compares raw generated bytes between Ubuntu and Windows in CI', () => {
		const workflow = readFileSync(new URL('../../../.github/workflows/ci.yml', import.meta.url), 'utf8');

		expect(workflow).toContain('runs-on: windows-latest');
		expect(workflow).toContain('token-byte-parity:');
		expect(workflow).toContain('cmp --silent');
		expect(workflow).toContain('run: bun run check');
		for (const path of artifactPaths) expect(workflow, path).toContain(path);
	});
});
